### ISSUE TITLE
[BUG] {카카오 닉네임 연동 안됨}

### ISSUE THREAD

**Issue by ZZ3n** [100-hours-a-week/5-team-ark-connectrip-be#101]
### 버그 현상 설명
버그는 아니고, 카카오 OAuth 로그인 이후 닉네임, 생년월일이 카카오와 연동이 안되어있습니다.

---

### 발생 과정
1. OAuth 로그인을 한다.
2. 그 후에 나오는 회원가입 페이지에서 발생한다.

---

### 예상 대책
OAuth 를 이용해서 닉네임, 생년월일 등의 값을 채워 넣는다.

---

### 스크린샷
<img width="565" alt="image" src="https://github.com/user-attachments/assets/b732ffaa-4fff-42d7-85f7-00ee1d9216f1">

---

### 기타 주석
😅😅

**Comment by 49EHyeon42** [comment]
유니크 닉네임을 사용하기 위해 카카오에서 제공된 이름을  사용하지 않기로 결정했습니다.
